<?php

define('ISLANDORA_INGEST_COLLECTIONS_DELIMITER',',');
define('ISLANDORA_INGEST_COLLECTIONS_ENCLOSURE','"');
define('ISLANDORA_INGEST_COLLECTIONS_ESCAPE','"');
/*
 * Retrieve the data from a DSV file, then for every entry
 * create a islandora collection 
 * 
 * 
 */
function populateIslandoraCollectionFromDsv($params) {
    $islandoraTuque = new IslandoraTuque();
    $islandoraSimpleDSVCollectionPopulator = new utkdigitalinitiatives\islandora\ingest\collections\IslandoraSimpleDSVCollectionPopulator($islandoraTuque, $params['create_node']);
    $collections_data = retrieveDataFromDsv($params['input']);
    $islandoraObjectModelLabelCache = new utkdigitalinitiatives\islandora\ingest\collections\IslandoraFedoraObjectLabelCache($islandoraTuque);

    foreach ($collections_data as $data) {
        $simpleDSVCollection =  new utkdigitalinitiatives\islandora\ingest\collections\SimpleDSVCollection($data, $islandoraObjectModelLabelCache);
          try {
              $islandoraSimpleDSVCollectionPopulator->islandoraIngestCollection($simpleDSVCollection);
          } catch (Exception $e) {
            $message = 'Error ingesting Islandora collection object ' . $simpleDSVCollection->getLabel() . "  PID: " . $simpleDSVCollection->getPid() . " :: " . $e->getMessage();
            drupal_set_message($message, 'error');
            watchdog($message, WATCHDOG_ERROR);
          }
    }
}


/**
 * Retrieve data from a delimiter-separated values file
 * The defaults assume a comma separated values file
 *
 * The DSV file must have the following columns:
 *   -title
 *   -cdm_alias (Text/Text field)
 *   -description (Long text/Textarea (multiple rows))
 *   -thumbnail (Image/Image)
 *   -object_id (Text/Text field)
 *
 * @param string $data_file_path
 *   The absolute filesystem path to the comma-separated-value file 
 * @param string $delimiter_char
 *   The optional delimiter parameter sets the field delimiter (one character only)
 *   Default is the ',' char, separates one data cell from another
 * @param string $enclosure_char
 *   The optional enclosure parameter sets the field enclosure character (one character only).
 *   The Default is '"' char, encapsulates the data cell data
 * @param string $escape_char
 *   The optional escape parameter sets the escape character (one character only). 
 *   The Default is '"', provides use of enclosure char with in data cell data
 * 
 */
function retrieveDataFromDsv($data_file_path, $delimiter_char = ISLANDORA_INGEST_COLLECTIONS_DELIMITER, 
            $enclosure_char = ISLANDORA_INGEST_COLLECTIONS_ENCLOSURE, $escape_char = ISLANDORA_INGEST_COLLECTIONS_ESCAPE) {
    $dsv_data = array();
    if (($data_file_handle = fopen($data_file_path, "r")) !== FALSE) {
        while (($dsv_row = fgetcsv($data_file_handle, 0, $delimiter_char, $enclosure_char,$escape_char)) !== FALSE) {
            // validate the number of rows first before adding to the data stack
            if (count($dsv_row) > 4) {
              $dsv_data[] = $dsv_row;
            }

        }
    } else {
        throw new Exception("Unable to open $data_file_path");
    }
    return $dsv_data;
}